# Generated by Django 5.1.3 on 2024-11-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_quiz_remove_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='quizzes', to='quiz.quiz'),
        ),
    ]
