# Generated by Django 5.1.3 on 2024-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_quiz_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=1),
        ),
    ]
