# Generated by Django 5.1.3 on 2024-11-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_questions',
            new_name='total_questions_attempted',
        ),
    ]
